### ISSUE TITLE
论文中的特征热图可视化

### ISSUE THREAD

**Issue by stanny880913** [Radar-Camera-Fusion/Awesome-Radar-Camera-Fusion#2]
您好，我观看了您的论文，想询问轮中的如下的热图您是怎么做出来的呢？请问有程式码范例可以参考嘛？谢谢您[
![Screenshot from 2024-06-18 14-03-38](https://github.com/Radar-Camera-Fusion/Awesome-Radar-Camera-Fusion/assets/56072246/eaf54097-9a93-44e8-ba76-4515f55f2a74)
](url)

**Comment by yaoshanliang** [comment]
Thanks for your interest in our work.  Detector heatmaps generated by the Grad-CAM [215] are utilized for
the result analysis of each method. To clearly show feature maps, only nine channels are selected for visualization.

**Comment by stanny880913** [comment]
> Thanks for your interest in our work. Detector heatmaps generated by the Grad-CAM [215] are utilized for the result analysis of each method. To clearly show feature maps, only nine channels are selected for visualization.

Hello, do the nine channels you refer to refer to the first nine channels? I want to apply it to my model, thank you
